import { Geist } from "next/font/google";
import TanstackProvider from "@/providers/TanstackProvider";
import CartProvider from "@/providers/CartProvider";
import SectionRenderer from "@/components/core/SectionRenderer";
import "./globals.css";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export async function generateMetadata() {
  const data = await fetch(
    "https://ecomback.bfinit.com/v2/store/global/meta/store",
    { cache: "no-store" },
  );

  const sections = await data.json();
  const metaInfo = sections?.data?.data?.[0];

  return {
    title: metaInfo?.Title || "Create Next App",
    description: metaInfo?.Description || "Generated by create next app",
  };
}

export default async function RootLayout({ children }) {
  const data = await fetch(
    "https://ecomback.bfinit.com/store/theme/data/695a0774722618f178d3d14c",
  );

  const sections = await data.json();

  return (
    <html lang="en" className={geist.variable}>
      <body className="font-geist antialiased">
        <TanstackProvider>
          <CartProvider>
            <SectionRenderer sections={sections?.data?.sections?.header} />
            {children}
            <SectionRenderer sections={sections?.data?.sections?.footer} />
          </CartProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
